### ISSUE TITLE
diagnostic-channel-publisher to support "pg-copy-streams"

### ISSUE THREAD

**Issue by cons0l3** [microsoft/node-diagnostic-channel#79] opened 2020-06-24 12:49 UTC
When executing a pg_copy_stream:

```
        const pool = new Pool(config.database_config);
        const copyFrom = require('pg-copy-streams').from;
        const { Readable } = require('stream');
        const createCsvWriter = require('csv-writer').createArrayCsvStringifier
        [...]
        var target = db.query(copyFrom(`COPY temptable (a,b,c) FROM STDIN DELIMITER ';' CSV HEADER':''}`));
        var source = Readable.from(await csvWriter.stringifyRecords(table_data));
        source.pipe(target);
```

The target variable is not of type Promise it is of type CopyStreamQuery extending Writeable. This of course ends in the error:

```
TypeError: queryResult.then is not a function
    at Client.query (D:\home\site\wwwroot\node_modules\diagnostic-channel-publishers\dist\src\pg.pub.js:245:18)
```

versions:
```
    "applicationinsights": "^1.7.5",
    "pg": "^8.2.1",
    "csv-writer": "^1.6.0",
    "pg-copy-streams": "^5.1.0"
```

"applicationinsights" pull dependency to:
```
        "diagnostic-channel": "0.2.0",
        "diagnostic-channel-publishers": "^0.3.4"
```

**Comment by markwolff** [comment] 2020-06-24 14:18
This seems like a dupe of #67. I'll look into this today

**Closed** 2020-06-24 14:18 UTC
